"models/v_ak47.mdl" "models/novaria_ze/merhabalarr_cs/kurovandal.mdl"

"models/v_m4a1.mdl" "models/novaria_ze/merhabalarr_cs/helezonphantom.mdl"

;"models/v_aug.mdl" "models/novaria_ze/merhabalarr_cs/v_aug.mdl"

"models/v_deagle.mdl" "models/novaria_ze/merhabalarr_cs/iyonsheriff.mdl"

"models/v_elite.mdl" "models/novaria_ze/merhabalarr_cs/yagmaccibandit.mdl"

"models/v_glock18.mdl" "models/novaria_ze/merhabalarr_cs/zifiriclassic.mdl"

"models/v_usp.mdl" "models/novaria_ze/merhabalarr_cs/ulupence_ghost.mdl"