; Model format: "Name" "Model" "Type" "Price" "Level" "Category(Karakter/Kanat)"
"Vandetta" "models/player/zpvandetta" "1" "500" "0" "Karakter"
"Pirate Girl" "models/player/zppirategirl" "1" "650" "0" "Karakter"
"Banana Man" "models/player/zpmuz" "1" "750" "0" "Karakter"
"Dead Pool" "models/player/zpdeadpool" "1" "650" "0" "Karakter"
"Batman" "models/player/zpbatman" "1" "500" "0" "Karakter"
"Smoke Wing" "models/novaria_ze/wingmodels/kanat.mdl" "1" "7500" "0" "Kanat"
"White Wing" "models/novaria_ze/wingmodels/1337wing.mdl" "1" "8000" "0" "Kanat"
"Devil Wing" "models/novaria_ze/wingmodels/devil_wings.mdl" "1" "8800" "0" "Kanat"
"Queen Wing" "models/novaria_ze/wingmodels/KraliceKanat.mdl" "1" "9800" "0" "Kanat"
"Royal Wing" "models/novaria_ze/wingmodels/KraliyetKanati.mdl" "1" "9800" "0" "Kanat"
"Dazzling Wing" "models/novaria_ze/wingmodels/KanatBlack.mdl" "1" "10000" "0" "Kanat"
