/*
 * =====================================================================
 *  Novaria Zombie Escape
 *  GitHub: https://github.com/merhabalarrdev
 * ---------------------------------------------------------------------
 *  [TR] Bu eklenti/paket Turkce olarak gelistirilmis ve topluluga
 *  UCRETSIZ olarak sunulmustur. Kaynak kodu ve derlenmis hali HICBIR
 *  SEKILDE PARAYLA SATILAMAZ, ticari amacla pazarlanamaz ya da kendi
 *  urununuzmus gibi el degistiremezsiniz. Kendi sunucunuzda ozgurce
 *  kullanabilir, inceleyebilir, duzenleyebilir ve gelistirebilirsiniz.
 *  Guncel surumu takip etmek icin lutfen yukaridaki GitHub sayfasini
 *  ziyaret edin. Firsatcilara karsi uyarilmis olun.
 *
 *  [EN] This plugin/package was developed in Turkish and is provided
 *  to the community FREE OF CHARGE. Neither the source code nor the
 *  compiled binary may be SOLD FOR MONEY, marketed commercially, or
 *  passed off as your own product under any circumstances. You are
 *  free to use, review, modify and improve it on your own server.
 *  Please visit the GitHub page above for the latest version. Be
 *  warned against opportunists reselling this content.
 *
 *  [KO] 이 플러그인/패키지는 터키어로 개발되었으며 커뮤니티에게
 *  무료로 제공됩니다. 소스 코드와 컴파일된 파일 모두 어떠한
 *  경우에도 판매하거나 상업적으로 거래하거나 자신의 제품인 것처럼
 *  둔갑시킬 수 없습니다. 자신의 서버에서 자유롭게 사용, 검토, 수정
 *  및 개선하실 수 있습니다. 최신 버전은 위의 GitHub 페이지를
 *  방문해 주세요. 무단 판매자들에게 경고합니다.
 * =====================================================================
 */
/* Plugin generated by AMXX-Studio */ 

#include <amxmodx> 
#include <amxmisc> 
#include <engine> 
#include <fakemeta_stocks> 
#include <fakemeta_util> 
#include <hamsandwich> 
#include <ham_const> 
#include <cstrike> 

#define PLUGIN "Anti-Bug" 
#define VERSION "1.0" 
#define AUTHOR "DPCS" 


new bugYapanlar[33] // Bug yapan oyuncularin listesi. 

new const Float:ctHasar = 15.0 // Bug yapan insanlara her adimda verilecek zarar 

new const Float:tHasar = 500.0 // Bug yapan zombilere her adimda verilecek zarar 

new const Float:incitmeSikligi = 0.6 // Bug yapanlara zarar verme sikligi (saniye cinsinden) 

public plugin_init() { 
     
    register_plugin(PLUGIN, VERSION, AUTHOR) 
    // Tasit araclarina bug yapildiginda bug_var fonksiyonu cagrilsin 
    RegisterHam(Ham_Blocked, "func_tracktrain", "bug_var") 
    set_task(incitmeSikligi,"zararVer",0,"",0,"b") 
} 


public bug_var(const this,const idother) 
{ 
    if (idother >= 1 && idother <= 32) // Sadece oyuncu olan entityler kayit altina alinir 
        bugYapanlar[idother] = true 
     
} 
public zararVer() 
{ 
     
    // Her oyuncu icin bug yapip yapmadigi kontrol edilsin 
    for (new i = 1; i < 33; i++) 
    { 
        if (bugYapanlar[i] && is_user_alive(i)) 
        { 
             
             
            client_print (i, print_center, "BUG YAPMA! / DON'T BUG!" ) 
             
            if (cs_get_user_team(i) == CsTeams:1) // zombi 
                fm_fakedamage(i, "", tHasar, DMG_GENERIC) 
            else if (cs_get_user_team(i) == CsTeams:2) // insan 
                fm_fakedamage(i, "", ctHasar, DMG_GENERIC) 
             
            bugYapanlar[i] = false // Ceza bitti. Hala bug devam ediyorsa bir daha True olur. 
             
        } 
    } 
     
} 